export enum Type {
  HOUSE = 'HOUSE',
  TRANSPORT = 'TRANSPORT',
  SUPERMARKET = 'SUPERMARKET',
  SHOPPING = 'SHOPPING',
  RESTAURANTS = 'RESTAURANTS',
  TRAVEL = 'TRAVEL',
  HEALTH = 'HEALTH',
  ENTRETAINMENT = 'ENTERTAINMENT',
  EDUCATION = 'EDUCATION',
  PERSONAL_CARE = 'PERSONAL_CARE',
  DEBTS = 'DEBTS',
  OTHERS = 'OTHERS',
}
